# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XN2XSwvwU8whX7rl-B0p3hqRsvLlKDZl
"""

# ============================================================
# Robust rPPG HR Estimation from Video
# Green + POS + CHROM + Improved Final HR Selection
# No sensor HR needed
# ============================================================

!pip install opencv-python scipy matplotlib numpy pandas -q

import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import butter, filtfilt, find_peaks, welch, detrend
from scipy.interpolate import interp1d
from google.colab import files
import os
import math

# -----------------------------
# Settings
# -----------------------------
MIN_HR = 40
MAX_HR = 140
LOW_HZ = MIN_HR / 60
HIGH_HZ = MAX_HR / 60

OUTPUT_DIR = "rppg_outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# -----------------------------
# Upload video
# -----------------------------
uploaded = files.upload()
video_path = list(uploaded.keys())[0]
print("Uploaded video:", video_path)

# -----------------------------
# Helper functions
# -----------------------------
def bandpass_filter(signal, fs, low=LOW_HZ, high=HIGH_HZ, order=3):
    signal = np.asarray(signal, dtype=np.float64)

    if len(signal) < fs * 3:
        return signal

    nyq = 0.5 * fs
    low = low / nyq
    high = high / nyq

    b, a = butter(order, [low, high], btype="band")
    try:
        return filtfilt(b, a, signal)
    except:
        return signal


def normalize_signal(x):
    x = np.asarray(x, dtype=np.float64)
    x = np.nan_to_num(x)
    x = detrend(x)

    std = np.std(x)
    if std < 1e-8:
        return x - np.mean(x)

    return (x - np.mean(x)) / std


def smooth_signal(x, window=5):
    x = np.asarray(x, dtype=np.float64)
    if len(x) < window:
        return x
    kernel = np.ones(window) / window
    return np.convolve(x, kernel, mode="same")


def estimate_fft_hr(sig, fs):
    sig = normalize_signal(sig)

    if len(sig) < fs * 5:
        return np.nan, 0

    nperseg = min(len(sig), int(fs * 12))
    freqs, power = welch(sig, fs=fs, nperseg=nperseg)

    mask = (freqs >= LOW_HZ) & (freqs <= HIGH_HZ)
    freqs = freqs[mask]
    power = power[mask]

    if len(power) == 0:
        return np.nan, 0

    idx = np.argmax(power)
    peak_freq = freqs[idx]
    hr = peak_freq * 60

    sorted_power = np.sort(power)
    if len(sorted_power) > 5:
        noise_floor = np.median(sorted_power)
    else:
        noise_floor = np.mean(sorted_power)

    conf = power[idx] / (noise_floor + 1e-8)

    return float(hr), float(conf)


def estimate_peak_hr(sig, fs):
    sig = normalize_signal(sig)

    min_dist = int(fs * 60 / MAX_HR)
    max_dist = int(fs * 60 / MIN_HR)

    if min_dist < 1:
        min_dist = 1

    prom = 0.25 * np.std(sig)

    peaks, props = find_peaks(
        sig,
        distance=min_dist,
        prominence=prom
    )

    if len(peaks) < 3:
        return np.nan, 0

    intervals = np.diff(peaks) / fs
    valid = (intervals >= 60 / MAX_HR) & (intervals <= 60 / MIN_HR)
    intervals = intervals[valid]

    if len(intervals) < 2:
        return np.nan, 0

    hr_values = 60 / intervals
    hr = np.median(hr_values)

    regularity = 1 / (np.std(hr_values) + 1e-8)
    conf = min(regularity / 10, 1.0)

    return float(hr), float(conf)


def pos_method(rgb, fs, window_sec=1.6):
    rgb = np.asarray(rgb, dtype=np.float64)
    n = rgb.shape[0]
    window = int(window_sec * fs)

    if window < 2:
        window = 2

    h = np.zeros(n)

    for start in range(0, n - window):
        end = start + window
        C = rgb[start:end, :]

        mean_color = np.mean(C, axis=0)
        mean_color[mean_color == 0] = 1e-8

        Cn = C / mean_color - 1

        X = 3 * Cn[:, 0] - 2 * Cn[:, 1]
        Y = 1.5 * Cn[:, 0] + Cn[:, 1] - 1.5 * Cn[:, 2]

        std_y = np.std(Y)
        if std_y < 1e-8:
            alpha = 0
        else:
            alpha = np.std(X) / std_y

        S = X - alpha * Y
        S = S - np.mean(S)

        h[start:end] += S

    return normalize_signal(h)


def chrom_method(rgb):
    rgb = np.asarray(rgb, dtype=np.float64)

    mean_color = np.mean(rgb, axis=0)
    mean_color[mean_color == 0] = 1e-8

    Cn = rgb / mean_color - 1

    R = Cn[:, 0]
    G = Cn[:, 1]
    B = Cn[:, 2]

    X = 3 * R - 2 * G
    Y = 1.5 * R + G - 1.5 * B

    std_y = np.std(Y)
    if std_y < 1e-8:
        alpha = 0
    else:
        alpha = np.std(X) / std_y

    S = X - alpha * Y
    return normalize_signal(S)


def get_face_detector():
    cascade_path = cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
    return cv2.CascadeClassifier(cascade_path)


def detect_face(frame, detector, previous_face=None):
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    faces = detector.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(80, 80)
    )

    if len(faces) == 0:
        return previous_face

    faces = sorted(faces, key=lambda f: f[2] * f[3], reverse=True)
    return faces[0]


def extract_rois(frame, face):
    x, y, w, h = face

    forehead = (
        int(x + 0.30 * w),
        int(y + 0.12 * h),
        int(0.40 * w),
        int(0.18 * h)
    )

    left_cheek = (
        int(x + 0.15 * w),
        int(y + 0.45 * h),
        int(0.22 * w),
        int(0.24 * h)
    )

    right_cheek = (
        int(x + 0.63 * w),
        int(y + 0.45 * h),
        int(0.22 * w),
        int(0.24 * h)
    )

    return forehead, left_cheek, right_cheek


def safe_roi_mean(frame, roi):
    x, y, w, h = roi

    H, W = frame.shape[:2]

    x = max(0, min(x, W - 1))
    y = max(0, min(y, H - 1))
    w = max(1, min(w, W - x))
    h = max(1, min(h, H - y))

    patch = frame[y:y+h, x:x+w]

    if patch.size == 0:
        return np.array([np.nan, np.nan, np.nan])

    rgb = cv2.cvtColor(patch, cv2.COLOR_BGR2RGB)
    return np.mean(rgb.reshape(-1, 3), axis=0)


def draw_rois(frame, face, rois):
    out = frame.copy()

    x, y, w, h = face
    cv2.rectangle(out, (x, y), (x+w, y+h), (0, 255, 0), 2)

    names = ["forehead", "left_cheek", "right_cheek"]
    colors = [(0, 0, 255), (255, 0, 0), (255, 0, 0)]

    for roi, name, color in zip(rois, names, colors):
        rx, ry, rw, rh = roi
        cv2.rectangle(out, (rx, ry), (rx+rw, ry+rh), color, 2)
        cv2.putText(
            out,
            name,
            (rx, ry - 5),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            color,
            2
        )

    return out


def calculate_quality(sig):
    sig = np.asarray(sig)
    if len(sig) < 5:
        return 0

    sig_std = np.std(sig)
    if sig_std < 1e-8:
        return 0

    diff_std = np.std(np.diff(sig))
    quality = sig_std / (diff_std + 1e-8)

    return float(quality)


def analyze_method(name, sig, fs):
    sig = normalize_signal(sig)
    sig_f = bandpass_filter(sig, fs)
    sig_f = smooth_signal(sig_f, window=3)

    fft_hr, fft_conf = estimate_fft_hr(sig_f, fs)
    peak_hr, peak_conf = estimate_peak_hr(sig_f, fs)
    quality = calculate_quality(sig_f)

    return {
        "name": name,
        "signal": sig,
        "filtered": sig_f,
        "fft_hr": fft_hr,
        "fft_conf": fft_conf,
        "peak_hr": peak_hr,
        "peak_conf": peak_conf,
        "quality": quality
    }


def choose_final_hr(results):
    candidates = []

    for name, r in results.items():
        candidates.append({
            "method": f"{name}_fft",
            "hr": r["fft_hr"],
            "conf": r["fft_conf"],
            "quality": r["quality"],
            "type": "fft",
            "source": name
        })

        candidates.append({
            "method": f"{name}_peak",
            "hr": r["peak_hr"],
            "conf": r["peak_conf"],
            "quality": r["quality"],
            "type": "peak",
            "source": name
        })

    candidates = [
        c for c in candidates
        if np.isfinite(c["hr"]) and MIN_HR <= c["hr"] <= MAX_HR
    ]

    if len(candidates) == 0:
        return np.nan, "no_valid_hr", []

    useful = []

    for c in candidates:
        hr = c["hr"]

        if c["type"] == "fft" and hr < 55:
            continue

        if c["type"] == "peak" and hr > 90:
            continue

        useful.append(c)

    if len(useful) < 2:
        useful = candidates.copy()

    # Agreement cluster
    best_cluster = []

    for c in useful:
        cluster = [
            x for x in useful
            if abs(x["hr"] - c["hr"]) <= 6
        ]

        if len(cluster) > len(best_cluster):
            best_cluster = cluster

    if len(best_cluster) >= 2:
        hrs = np.array([c["hr"] for c in best_cluster])
        confs = np.array([max(c["conf"], 0.1) for c in best_cluster])
        qualities = np.array([max(c["quality"], 0.1) for c in best_cluster])

        weights = confs * qualities
        weights = weights / np.sum(weights)

        weighted_hr = float(np.sum(hrs * weights))
        median_hr = float(np.median(hrs))

        final_hr = 0.55 * median_hr + 0.45 * weighted_hr

        return final_hr, "agreement_cluster_weighted_median", candidates

    # Rescue logic for moving-head videos
    pos_peak = None
    chrom_fft = None
    chrom_peak = None
    green_peak = None
    green_fft = None

    for c in candidates:
        if c["method"] == "pos_peak":
            pos_peak = c["hr"]
        elif c["method"] == "chrom_fft":
            chrom_fft = c["hr"]
        elif c["method"] == "chrom_peak":
            chrom_peak = c["hr"]
        elif c["method"] == "green_peak":
            green_peak = c["hr"]
        elif c["method"] == "green_fft":
            green_fft = c["hr"]

    rescue_values = []

    for v in [pos_peak, chrom_fft, chrom_peak, green_peak, green_fft]:
        if v is not None and np.isfinite(v) and 55 <= v <= 88:
            rescue_values.append(v)

    if len(rescue_values) >= 2:
        rescue_values = np.array(rescue_values)

        q1 = np.percentile(rescue_values, 25)
        q3 = np.percentile(rescue_values, 75)
        iqr = q3 - q1

        filtered = rescue_values[
            (rescue_values >= q1 - 1.5 * iqr) &
            (rescue_values <= q3 + 1.5 * iqr)
        ]

        if len(filtered) == 0:
            filtered = rescue_values

        final_hr = float(np.median(filtered))
        return final_hr, "motion_rescue_median", candidates

    # Score fallback
    for c in useful:
        hr = c["hr"]
        score = 0

        if 58 <= hr <= 85:
            score += 6
        elif 50 <= hr < 58:
            score += 2
        elif 85 < hr <= 95:
            score += 1
        else:
            score -= 3

        if c["type"] == "peak":
            score += 0.8

        if c["source"] == "pos":
            score += 0.8
        elif c["source"] == "chrom":
            score += 0.6
        elif c["source"] == "green":
            score += 0.3

        score += min(c["conf"], 5) * 0.25
        score += min(c["quality"], 5) * 0.2

        if hr < 55:
            score -= 4

        if hr > 90:
            score -= 5

        c["score"] = score

    best = max(useful, key=lambda x: x["score"])

    return float(best["hr"]), best["method"] + "_score_selected", candidates


# -----------------------------
# Read video and extract signals
# -----------------------------
cap = cv2.VideoCapture(video_path)

fps = cap.get(cv2.CAP_PROP_FPS)
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
duration = frame_count / fps if fps > 0 else 0

print("Video FPS:", fps)
print("Frames:", frame_count)
print("Duration:", duration)

detector = get_face_detector()

times = []
rgb_values = []
motion_values = []
valid_frames = []

previous_face = None
preview_frames = []

frame_idx = 0

while True:
    ret, frame = cap.read()
    if not ret:
        break

    t = frame_idx / fps

    face = detect_face(frame, detector, previous_face)

    if face is not None:
        previous_face = face

        forehead, left_cheek, right_cheek = extract_rois(frame, face)

        rgb_forehead = safe_roi_mean(frame, forehead)
        rgb_left = safe_roi_mean(frame, left_cheek)
        rgb_right = safe_roi_mean(frame, right_cheek)

        rgb_mean = np.nanmean(
            np.vstack([rgb_forehead, rgb_left, rgb_right]),
            axis=0
        )

        if np.all(np.isfinite(rgb_mean)):
            times.append(t)
            rgb_values.append(rgb_mean)
            valid_frames.append(frame_idx)

        if len(preview_frames) < 6:
            preview = draw_rois(frame, face, [forehead, left_cheek, right_cheek])
            preview_frames.append(cv2.cvtColor(preview, cv2.COLOR_BGR2RGB))

    frame_idx += 1

cap.release()

times = np.asarray(times)
rgb_values = np.asarray(rgb_values)

print("Extracted samples:", len(rgb_values))

if len(rgb_values) < 50:
    raise ValueError("Not enough valid face samples. Try a clearer video.")

# -----------------------------
# Preview frames
# -----------------------------
print("Preview frames:")
print("Green rectangle = face")
print("Red rectangle = forehead")
print("Blue rectangles = cheeks")

for img in preview_frames:
    plt.figure(figsize=(10, 5))
    plt.imshow(img)
    plt.axis("off")
    plt.show()

# -----------------------------
# Resample to stable sampling rate
# -----------------------------
estimated_fs = 1 / np.median(np.diff(times))
print("Estimated sampling rate:", estimated_fs)

target_fs = min(max(estimated_fs, 20), 30)

uniform_times = np.arange(times[0], times[-1], 1 / target_fs)

rgb_resampled = np.zeros((len(uniform_times), 3))

for i in range(3):
    f = interp1d(
        times,
        rgb_values[:, i],
        kind="linear",
        fill_value="extrapolate"
    )
    rgb_resampled[:, i] = f(uniform_times)

fs = target_fs

# -----------------------------
# Build rPPG signals
# -----------------------------
green_signal = rgb_resampled[:, 1]
pos_signal = pos_method(rgb_resampled, fs)
chrom_signal = chrom_method(rgb_resampled)

results = {
    "green": analyze_method("green", green_signal, fs),
    "pos": analyze_method("pos", pos_signal, fs),
    "chrom": analyze_method("chrom", chrom_signal, fs)
}

final_hr, final_method, candidates = choose_final_hr(results)

# -----------------------------
# Print results
# -----------------------------
print("\n========== GLOBAL RESULTS ==========\n")

for name, r in results.items():
    print(f"--- {name.upper()} ---")
    print(f"FFT HR: {r['fft_hr']:.2f} bpm | conf: {r['fft_conf']:.2f}")
    print(f"Peak HR: {r['peak_hr']:.2f} bpm | conf: {r['peak_conf']:.2f}")
    print(f"Quality: {r['quality']:.2f}")
    print()

print("========== FINAL RESULT ==========")
print(f"Final HR: {final_hr:.2f} bpm")
print(f"Final method: {final_method}")

# -----------------------------
# Save CSV
# -----------------------------
df = pd.DataFrame({
    "time_sec": uniform_times,
    "green_raw": normalize_signal(green_signal),
    "pos_raw": normalize_signal(pos_signal),
    "chrom_raw": normalize_signal(chrom_signal),
    "green_filtered": results["green"]["filtered"],
    "pos_filtered": results["pos"]["filtered"],
    "chrom_filtered": results["chrom"]["filtered"]
})

csv_path = os.path.join(OUTPUT_DIR, "rppg_results.csv")
df.to_csv(csv_path, index=False)

print("CSV saved:", csv_path)

# -----------------------------
# Plot filtered signals
# -----------------------------
plt.figure(figsize=(14, 5))
plt.plot(uniform_times, results["green"]["filtered"], label="Green filtered")
plt.plot(uniform_times, results["pos"]["filtered"], label="POS filtered")
plt.plot(uniform_times, results["chrom"]["filtered"], label="CHROM filtered")
plt.title(f"Filtered rPPG Signals | Final HR={final_hr:.2f} bpm")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.grid(True)
plt.legend()
plt.show()

# -----------------------------
# Plot FFT spectrum
# -----------------------------
plt.figure(figsize=(14, 5))

for name, r in results.items():
    sig = r["filtered"]
    freqs, power = welch(sig, fs=fs, nperseg=min(len(sig), int(fs * 12)))
    bpm = freqs * 60
    mask = (bpm >= MIN_HR) & (bpm <= MAX_HR)
    plt.plot(bpm[mask], power[mask], label=f"{name.upper()} spectrum")

plt.axvline(final_hr, linestyle="--", label=f"Final HR={final_hr:.2f}")
plt.title("FFT Spectrum Comparison")
plt.xlabel("Heart Rate (BPM)")
plt.ylabel("FFT Magnitude")
plt.grid(True)
plt.legend()
plt.show()

# -----------------------------
# Peak detection plot on POS
# -----------------------------
pos_f = results["pos"]["filtered"]
min_dist = int(fs * 60 / MAX_HR)
peaks, _ = find_peaks(
    normalize_signal(pos_f),
    distance=max(min_dist, 1),
    prominence=0.25 * np.std(pos_f)
)

plt.figure(figsize=(14, 5))
plt.plot(uniform_times, pos_f, label="POS filtered")
plt.scatter(uniform_times[peaks], pos_f[peaks], marker="x", label="Detected POS peaks")
plt.title("Peak Detection on POS rPPG Signal")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.grid(True)
plt.legend()
plt.show()